/*
Copyright © 2025 Donald Gifford

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/donaldgifford/rex/internal/db"
	"github.com/spf13/cobra"
)

var adrUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update ADR README file",
	Long: `Update the ADR README.md file with a table of all ADRs.

This command:
- Queries all ADRs from the cache
- Generates a markdown table with ADR details
- Updates the README.md file (preserving content outside auto-generated section)

The generated section is placed between:
  <!-- BEGIN AUTO-GENERATED -->
  <!-- END AUTO-GENERATED -->

Example:
  rex adr update`,
	RunE: func(cmd *cobra.Command, args []string) error {
		docsDir, err := cmd.Flags().GetString("docs-dir")
		if err != nil {
			return err
		}

		// Make docs dir absolute
		docsDir, err = filepath.Abs(docsDir)
		if err != nil {
			return fmt.Errorf("resolve docs dir: %w", err)
		}

		// Open database
		dbPath := filepath.Join(docsDir, "..", ".rex.db")
		database, err := db.Open(dbPath)
		if err != nil {
			return fmt.Errorf("open database: %w", err)
		}
		defer database.Close()

		// Auto-rebuild if needed
		needsRebuild, err := database.NeedsRebuild(docsDir)
		if err != nil {
			return fmt.Errorf("check rebuild: %w", err)
		}
		if needsRebuild {
			fmt.Println("Cache is stale, rebuilding...")
			if err := database.Rebuild(docsDir); err != nil {
				return fmt.Errorf("rebuild cache: %w", err)
			}
		}

		// Get all ADRs
		adrs, err := database.ListADRs("")
		if err != nil {
			return fmt.Errorf("list ADRs: %w", err)
		}

		// Get stats
		stats, err := database.GetADRStats()
		if err != nil {
			return fmt.Errorf("get stats: %w", err)
		}

		// Generate ADR table
		adrTable := generateADRTable(adrs, stats)

		// Read existing README
		adrDir := filepath.Join(docsDir, "adr")
		readmePath := filepath.Join(adrDir, "README.md")

		var existingContent string
		if content, err := os.ReadFile(readmePath); err == nil {
			existingContent = string(content)
		}

		// Update README with auto-generated section
		updatedContent := updateAutoGeneratedSection(existingContent, adrTable)

		// Write README
		if err := os.WriteFile(readmePath, []byte(updatedContent), 0644); err != nil {
			return fmt.Errorf("write README: %w", err)
		}

		fmt.Printf("✓ Updated %s\n", readmePath)
		fmt.Printf("  Total ADRs: %d\n", len(adrs))
		if len(stats) > 0 {
			fmt.Print("  By status: ")
			first := true
			for status, count := range stats {
				if !first {
					fmt.Print(", ")
				}
				fmt.Printf("%s: %d", status, count)
				first = false
			}
			fmt.Println()
		}

		return nil
	},
}

func generateADRTable(adrs []*db.ADR, stats map[string]int) string {
	var sb strings.Builder

	sb.WriteString("## All ADRs\n\n")

	// Summary stats
	total := 0
	for _, count := range stats {
		total += count
	}
	sb.WriteString(fmt.Sprintf("**Total**: %d ADRs\n\n", total))

	if len(stats) > 0 {
		sb.WriteString("**By Status**:\n")
		statusOrder := []string{"draft", "accepted", "deprecated", "superseded"}
		for _, status := range statusOrder {
			if count, ok := stats[status]; ok {
				emoji := getStatusEmoji(status)
				sb.WriteString(fmt.Sprintf("- %s %s: %d\n", emoji, status, count))
			}
		}
		sb.WriteString("\n")
	}

	// Table
	sb.WriteString("| Number | Status | Title | Date |\n")
	sb.WriteString("|--------|--------|-------|------|\n")

	for _, adr := range adrs {
		emoji := getStatusEmoji(adr.Status)
		filename := filepath.Base(adr.FilePath)
		sb.WriteString(fmt.Sprintf("| %04d | %s %s | [%s](%s) | %s |\n",
			adr.Number,
			emoji,
			adr.Status,
			adr.Title,
			filename,
			adr.Date,
		))
	}

	return sb.String()
}

func getStatusEmoji(status string) string {
	switch status {
	case "draft":
		return "📝"
	case "accepted":
		return "✅"
	case "deprecated":
		return "⚠️"
	case "superseded":
		return "🔄"
	default:
		return "  "
	}
}

func updateAutoGeneratedSection(existingContent, newContent string) string {
	beginMarker := "<!-- BEGIN AUTO-GENERATED -->"
	endMarker := "<!-- END AUTO-GENERATED -->"

	// Find markers
	beginIdx := strings.Index(existingContent, beginMarker)
	endIdx := strings.Index(existingContent, endMarker)

	if beginIdx == -1 || endIdx == -1 {
		// No markers found, create default content with markers
		return createDefaultReadme(newContent)
	}

	// Preserve content before BEGIN marker
	before := existingContent[:beginIdx+len(beginMarker)]

	// Preserve content after END marker
	after := existingContent[endIdx:]

	// Combine
	return before + "\n" + newContent + "\n" + after
}

func createDefaultReadme(generatedContent string) string {
	return `# Architecture Decision Records (ADRs)

This directory contains Architecture Decision Records documenting significant
technical decisions made during the development of this project.

## What are ADRs?

ADRs document **technical implementation decisions** for specific architectural
components. Each ADR focuses on a single decision and includes:

- **Context**: The problem or constraint that led to this decision
- **Decision**: What was chosen and why
- **Consequences**: Trade-offs, pros, and cons
- **Alternatives**: Other options that were considered

## Creating a New ADR

` + "```bash" + `
rex adr create "Your ADR Title"
` + "```" + `

This will create a new ADR file with an auto-incremented number.

## ADR Status

- **draft**: Under discussion, not yet approved
- **accepted**: Approved and being implemented or already implemented
- **deprecated**: No longer relevant
- **superseded**: Replaced by another ADR

<!-- BEGIN AUTO-GENERATED -->
` + generatedContent + `
<!-- END AUTO-GENERATED -->
`
}

func init() {
	adrCmd.AddCommand(adrUpdateCmd)
	adrUpdateCmd.Flags().StringP("docs-dir", "d", "docs", "Documentation directory")
}
