/*
Copyright © 2025 Donald Gifford

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/donaldgifford/rex/internal/db"
	"github.com/spf13/cobra"
)

var planUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update plan README file",
	Long: `Update the plans README.md file with a table of all plans.

This command:
- Queries all plans from the cache
- Generates a markdown table with plan details
- Updates the README.md file (preserving content outside auto-generated section)

The generated section is placed between:
  <!-- BEGIN AUTO-GENERATED -->
  <!-- END AUTO-GENERATED -->

Example:
  rex plan update`,
	RunE: func(cmd *cobra.Command, args []string) error {
		docsDir, err := cmd.Flags().GetString("docs-dir")
		if err != nil {
			return err
		}

		// Make docs dir absolute
		docsDir, err = filepath.Abs(docsDir)
		if err != nil {
			return fmt.Errorf("resolve docs dir: %w", err)
		}

		// Open database
		dbPath := filepath.Join(docsDir, "..", ".rex.db")
		database, err := db.Open(dbPath)
		if err != nil {
			return fmt.Errorf("open database: %w", err)
		}
		defer database.Close()

		// Auto-rebuild if needed
		needsRebuild, err := database.NeedsRebuild(docsDir)
		if err != nil {
			return fmt.Errorf("check rebuild: %w", err)
		}
		if needsRebuild {
			fmt.Println("Cache is stale, rebuilding...")
			if err := database.Rebuild(docsDir); err != nil {
				return fmt.Errorf("rebuild cache: %w", err)
			}
		}

		// Get all plans
		plans, err := database.ListPlans("")
		if err != nil {
			return fmt.Errorf("list plans: %w", err)
		}

		// Get stats
		stats, err := database.GetPlanStats()
		if err != nil {
			return fmt.Errorf("get stats: %w", err)
		}

		// Generate plan table
		planTable := generatePlanTable(plans, stats)

		// Read existing README
		planDir := filepath.Join(docsDir, "plans")
		readmePath := filepath.Join(planDir, "README.md")

		var existingContent string
		if content, err := os.ReadFile(readmePath); err == nil {
			existingContent = string(content)
		}

		// Update README with auto-generated section
		updatedContent := updateAutoGeneratedSection(existingContent, planTable)

		// Ensure plans directory exists
		if err := os.MkdirAll(planDir, 0755); err != nil {
			return fmt.Errorf("create plans directory: %w", err)
		}

		// Write README
		if err := os.WriteFile(readmePath, []byte(updatedContent), 0644); err != nil {
			return fmt.Errorf("write README: %w", err)
		}

		fmt.Printf("✓ Updated %s\n", readmePath)
		fmt.Printf("  Total plans: %d\n", len(plans))
		if len(stats) > 0 {
			fmt.Print("  By status: ")
			first := true
			for status, count := range stats {
				if !first {
					fmt.Print(", ")
				}
				fmt.Printf("%s: %d", status, count)
				first = false
			}
			fmt.Println()
		}

		return nil
	},
}

func generatePlanTable(plans []*db.Plan, stats map[string]int) string {
	var sb strings.Builder

	sb.WriteString("## All Plans\n\n")

	// Summary stats
	total := 0
	for _, count := range stats {
		total += count
	}
	sb.WriteString(fmt.Sprintf("**Total**: %d plans\n\n", total))

	if len(stats) > 0 {
		sb.WriteString("**By Status**:\n")
		statusOrder := []string{"draft", "active", "completed", "cancelled"}
		for _, status := range statusOrder {
			if count, ok := stats[status]; ok {
				emoji := getPlanStatusEmoji(status)
				sb.WriteString(fmt.Sprintf("- %s %s: %d\n", emoji, status, count))
			}
		}
		sb.WriteString("\n")
	}

	// Table
	sb.WriteString("| Number | Status | Title | Created |\n")
	sb.WriteString("|--------|--------|-------|----------|\n")

	for _, plan := range plans {
		emoji := getPlanStatusEmoji(plan.Status)
		filename := filepath.Base(plan.FilePath)
		sb.WriteString(fmt.Sprintf("| %04d | %s %s | [%s](%s) | %s |\n",
			plan.Number,
			emoji,
			plan.Status,
			plan.Title,
			filename,
			plan.CreatedDate,
		))
	}

	return sb.String()
}

func getPlanStatusEmoji(status string) string {
	switch status {
	case "draft":
		return "📝"
	case "active":
		return "🔨"
	case "completed":
		return "✅"
	case "cancelled":
		return "❌"
	default:
		return "  "
	}
}

func init() {
	planCmd.AddCommand(planUpdateCmd)
	planUpdateCmd.Flags().StringP("docs-dir", "d", "docs", "Documentation directory")
}
