/*
Copyright © 2025 Donald Gifford

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
*/
package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/donaldgifford/rex/internal/db"
	"github.com/spf13/cobra"
)

var rfcUpdateCmd = &cobra.Command{
	Use:   "update",
	Short: "Update RFC README file",
	Long: `Update the RFC README.md file with a table of all RFCs.

This command:
- Queries all RFCs from the cache
- Generates a markdown table with RFC details
- Updates the README.md file (preserving content outside auto-generated section)

The generated section is placed between:
  <!-- BEGIN AUTO-GENERATED -->
  <!-- END AUTO-GENERATED -->

Example:
  rex rfc update`,
	RunE: func(cmd *cobra.Command, args []string) error {
		docsDir, err := cmd.Flags().GetString("docs-dir")
		if err != nil {
			return err
		}

		// Make docs dir absolute
		docsDir, err = filepath.Abs(docsDir)
		if err != nil {
			return fmt.Errorf("resolve docs dir: %w", err)
		}

		// Open database
		dbPath := filepath.Join(docsDir, "..", ".rex.db")
		database, err := db.Open(dbPath)
		if err != nil {
			return fmt.Errorf("open database: %w", err)
		}
		defer database.Close()

		// Auto-rebuild if needed
		needsRebuild, err := database.NeedsRebuild(docsDir)
		if err != nil {
			return fmt.Errorf("check rebuild: %w", err)
		}
		if needsRebuild {
			fmt.Println("Cache is stale, rebuilding...")
			if err := database.Rebuild(docsDir); err != nil {
				return fmt.Errorf("rebuild cache: %w", err)
			}
		}

		// Get all RFCs
		rfcs, err := database.ListRFCs("")
		if err != nil {
			return fmt.Errorf("list RFCs: %w", err)
		}

		// Get stats
		stats, err := database.GetRFCStats()
		if err != nil {
			return fmt.Errorf("get stats: %w", err)
		}

		// Generate RFC table
		rfcTable := generateRFCTable(rfcs, stats)

		// Read existing README
		rfcDir := filepath.Join(docsDir, "rfc")
		readmePath := filepath.Join(rfcDir, "README.md")

		var existingContent string
		if content, err := os.ReadFile(readmePath); err == nil {
			existingContent = string(content)
		}

		// Update README with auto-generated section
		updatedContent := updateAutoGeneratedSection(existingContent, rfcTable)

		// Ensure RFC directory exists
		if err := os.MkdirAll(rfcDir, 0755); err != nil {
			return fmt.Errorf("create RFC directory: %w", err)
		}

		// Write README
		if err := os.WriteFile(readmePath, []byte(updatedContent), 0644); err != nil {
			return fmt.Errorf("write README: %w", err)
		}

		fmt.Printf("✓ Updated %s\n", readmePath)
		fmt.Printf("  Total RFCs: %d\n", len(rfcs))
		if len(stats) > 0 {
			fmt.Print("  By status: ")
			first := true
			for status, count := range stats {
				if !first {
					fmt.Print(", ")
				}
				fmt.Printf("%s: %d", status, count)
				first = false
			}
			fmt.Println()
		}

		return nil
	},
}

func generateRFCTable(rfcs []*db.RFC, stats map[string]int) string {
	var sb strings.Builder

	sb.WriteString("## All RFCs\n\n")

	// Summary stats
	total := 0
	for _, count := range stats {
		total += count
	}
	sb.WriteString(fmt.Sprintf("**Total**: %d RFCs\n\n", total))

	if len(stats) > 0 {
		sb.WriteString("**By Status**:\n")
		statusOrder := []string{"draft", "review", "approved", "implemented", "rejected"}
		for _, status := range statusOrder {
			if count, ok := stats[status]; ok {
				emoji := getRFCStatusEmoji(status)
				sb.WriteString(fmt.Sprintf("- %s %s: %d\n", emoji, status, count))
			}
		}
		sb.WriteString("\n")
	}

	// Table
	sb.WriteString("| Number | Status | Title | Author | Created |\n")
	sb.WriteString("|--------|--------|-------|--------|----------|\n")

	for _, rfc := range rfcs {
		emoji := getRFCStatusEmoji(rfc.Status)
		filename := filepath.Base(rfc.FilePath)
		author := rfc.Author
		if author == "" {
			author = "-"
		}
		sb.WriteString(fmt.Sprintf("| %04d | %s %s | [%s](%s) | %s | %s |\n",
			rfc.Number,
			emoji,
			rfc.Status,
			rfc.Title,
			filename,
			author,
			rfc.CreatedDate,
		))
	}

	return sb.String()
}

func getRFCStatusEmoji(status string) string {
	switch status {
	case "draft":
		return "📝"
	case "review":
		return "👀"
	case "approved":
		return "✅"
	case "implemented":
		return "🚀"
	case "rejected":
		return "❌"
	default:
		return "  "
	}
}

func init() {
	rfcCmd.AddCommand(rfcUpdateCmd)
	rfcUpdateCmd.Flags().StringP("docs-dir", "d", "docs", "Documentation directory")
}
