# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
        name: Checkout

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23.4"

      - name: Build Linux
        run: CGO_ENABLED=0 GOOS="linux" GOARCH="amd64" go build -o rex_linux_amd64 .

      - name: Test CLI Run
        run: ./rex_linux_amd64 -h
